<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\DoctorPrescriptionimage\**" />
    <Compile Remove="wwwroot\Funeralimg\**" />
    <Content Remove="wwwroot\DoctorPrescriptionimage\**" />
    <Content Remove="wwwroot\Funeralimg\**" />
    <EmbeddedResource Remove="wwwroot\DoctorPrescriptionimage\**" />
    <EmbeddedResource Remove="wwwroot\Funeralimg\**" />
    <None Remove="wwwroot\DoctorPrescriptionimage\**" />
    <None Remove="wwwroot\Funeralimg\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="itext7" Version="9.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PDFsharp" Version="6.2.2" />
    <PackageReference Include="QuestPDF" Version="2025.7.3" />
    <PackageReference Include="Twilio" Version="7.13.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\HospitalAssistanceFileStorage\" />
    <Folder Include="wwwroot\FuneralAssistanceFileStorage\" />
    <Folder Include="wwwroot\OtherAssistanceFileStorage\" />
    <Folder Include="wwwroot\Validimg\" />
    <Folder Include="wwwroot\UsersImg\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\verification-ocr-progress-integration.js" />
  </ItemGroup>

</Project>
